{"uuid": "06046391-80a0-45db-99bf-c59c223ef476", "children": ["c339a994-7d6b-4c50-816e-b75e0ec50954"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=131.0.6778.109)\nStacktrace:\n\tGetHandleVerifier [0x00007FF629836CF5+28821]\n\t(No symbol) [0x00007FF6297A3880]\n\t(No symbol) [0x00007FF62964578A]\n\t(No symbol) [0x00007FF629642E88]\n\t(No symbol) [0x00007FF629633BF9]\n\t(No symbol) [0x00007FF62963594F]\n\t(No symbol) [0x00007FF629633EBF]\n\t(No symbol) [0x00007FF62963371B]\n\t(No symbol) [0x00007FF62963365A]\n\t(No symbol) [0x00007FF629631274]\n\t(No symbol) [0x00007FF629631B3C]\n\t(No symbol) [0x00007FF62964885A]\n\t(No symbol) [0x00007FF6296E01FE]\n\t(No symbol) [0x00007FF6296BF2FA]\n\t(No symbol) [0x00007FF6296DF412]\n\t(No symbol) [0x00007FF6296BF0A3]\n\t(No symbol) [0x00007FF62968A778]\n\t(No symbol) [0x00007FF62968B8E1]\n\tGetHandleVerifier [0x00007FF629B6FCED+3408013]\n\tGetHandleVerifier [0x00007FF629B8745F+3504127]\n\tGetHandleVerifier [0x00007FF629B7B63D+3455453]\n\tGetHandleVerifier [0x00007FF6298FBDFB+835995]\n\t(No symbol) [0x00007FF6297AEB9F]\n\t(No symbol) [0x00007FF6297AA854]\n\t(No symbol) [0x00007FF6297AA9ED]\n\t(No symbol) [0x00007FF62979A1D9]\n\tBaseThreadInitThunk [0x00007FFE76E27374+20]\n\tRtlUserThreadStart [0x00007FFE7723CC91+33]\n\n", "trace": "  File \"D:\\Batch Notes\\PythonAutomation\\CT19\\BankApp_Pytest\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Batch Notes\\PythonAutomation\\CT19\\BankApp_Pytest\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\Batch Notes\\PythonAutomation\\CT19\\BankApp_Pytest\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Batch Notes\\PythonAutomation\\CT19\\BankApp_Pytest\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Batch Notes\\PythonAutomation\\CT19\\BankApp_Pytest\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\Batch Notes\\PythonAutomation\\CT19\\BankApp_Pytest\\testCases\\conftest.py\", line 25, in setup\n    driver.get(\"https://bankapp.credence.in/\")\n  File \"D:\\Batch Notes\\PythonAutomation\\CT19\\BankApp_Pytest\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 393, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"D:\\Batch Notes\\PythonAutomation\\CT19\\BankApp_Pytest\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Batch Notes\\PythonAutomation\\CT19\\BankApp_Pytest\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1733804392451, "stop": 1733804399399}], "start": 1733804392451, "stop": 1733804399518}